name: containerAction
description: containerAction
inputs:
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0

outputs:
  result:
    description: 'output of sum of two values'

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.number1 }}
    - ${{ inputs.number2 }}