name: artifacts
on:
  push:

jobs:
  upload-artifact:
    name: upload artifact
    runs-on: ubuntu-latest
    steps:
      - run: docker info > myArtifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myArtifact.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: display list of files
        run: ls -R
      - run: cat myArtifact.txt
