name: cache
on: workflow_dispatch

jobs:
  test-cache:
    name: job to test cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache local Maven repository
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-