name: Sonar run
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, reopened, opened]
jobs:
  sonar:
    name: Sonar run
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Cache Sonar
        uses: actions/cache@v3
        with:
          path: '~/.sonar/cache'
          key: ${{runner.os}}-sonar
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '~/m2/repository'
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-maven-
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Print github metadata
        run: echo "${{toJSON(github)}}"

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -DskipITs \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=ryhaldenys \
          -Dsonar.projectKey=ryhaldenys_actions-demo \
          -Dsonar.projectName="${{github.event.repository.name}}" \
          -Dsonar.projectVersion="${{github.event.repository.name}}" \
          -Dsonar.coverage.jacoco.xmlReportPaths="${{ github.workspace }}/jacoco-report/target/site/jacoco-aggregate/jacoco.xml"