name: Variables and secrets

env:
  WF_VAR: "Workflow level var"

on:
  workflow_dispatch:
  push:

jobs:
  test_vaiables:
    env:
      JOB_VAR: "Job level var"

    name: job to test vars
    runs-on: ubuntu-latest
    steps:
      - name: test vars
        env:
          STEP_VAR: "Step level var"
        id: spepVar
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
        
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
